project:
  type: website
  output-dir: .
  render:
    - index.qmd
  resources:
    - Visualizations/**
    - capstone_files/**
    - index.qmd

execute:
  enabled: false
  freeze: auto

format:
  html:
    toc: true
    number-sections: true
    theme:
      light: lightly
      dark: darkly
